src/objects/Default_Attachment_Description__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Description__c</fullName>
        <description>The default description for attachment used in Survey Guru</description>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Default Attachment Description</label>
</CustomObject>

src/objects/Trifecta_Survey__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the survey</description>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Trifecta Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trifecta Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TTISGShareLinkPageController.cls
public with sharing class TTISGShareLinkPageController {
	public String submissionId;
	public String surveyId;

	public TTISGShareLinkPageController() {
		submissionId = ApexPages.currentPage().getParameters().get('Id');
		surveyId = ApexPages.currentPage().getParameters().get('Survey');
	}
	public PageReference createChatterPostAndRedirect(){

	  PageReference pref = new PageReference('/apex/TTISGShareSubmissionToChatter');
	  pref.getParameters().put('Id',submissionId);
	  pref.getParameters().put('Survey',surveyId);

	  Trifecta_Survey__c survey = new TTISGSurveyService().getSurveyById(surveyId);

      Attachment a = new Attachment();
      a.Body = pref.getContentAsPDF();
      a.ParentID = submissionId;
      a.Name = survey.Name+'.pdf';
      insert a;
	  
	  FeedItem chatterItem = new FeedItem();
	  chatterItem.parentId = a.ParentId;
	  chatterItem.ContentData = a.body;
	  chatterItem.ContentFileName = a.Name;
	  chatterItem.ContentDescription = Default_Attachment_Description__c.getOrgDefaults().Description__c != null ? Default_Attachment_Description__c.getOrgDefaults().Description__c : 'Sample Description';
	  insert chatterItem;

	  return new PageReference('/_ui/core/userprofile/UserProfilePage?u='+UserInfo.getUserId());
	}
}