src/objects/Survey_Global_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>setting for public site URL</description>
    <fields>
        <fullName>Login_URL__c</fullName>
        <label>Login URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Address__c</fullName>
        <label>Site Address</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Survey Global Settings</label>
</CustomObject>

src/objects/Trifecta_Survey__c.object
<CustomObject>
    <label>Trifecta Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trifecta Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Trifecta_Survey_Submission__c.object
<CustomObject>
    <description>Junction object to link up Survey and User/Contact to whom the survey is submitted.</description>
    <fields>
        <fullName>Avg_Weightage__c</fullName>
        <formula>IF( noOfWeightages__c &gt; 0, sumOfWeightage__c / noOfWeightages__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Avg.Weightage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Submitted_To_Name__c</fullName>
        <label>Submitted To</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Submitted_To__c</fullName>
        <description>Id of User/Contact</description>
        <label>Submitted To</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <description>Survey which is submitted</description>
        <label>Survey</label>
        <referenceTo>Trifecta_Survey__c</referenceTo>
        <relationshipLabel>Trifecta Survey Submissions</relationshipLabel>
        <relationshipName>Trifecta_Survey_Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Trifecta Survey Submission</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Trifecta Survey Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trifecta Survey Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TTISGSendEmailComponentController.cls
public with sharing class TTISGSendEmailComponentController {
    public String submissionId { get; set; }
    public String senderId { get; set; }
    public String SurveyURL {get; set;}
    public Decimal avgWeightage {get; set;}
    public String submittedToName {
        get {
            Trifecta_Survey_Submission__c submission = [select Submitted_To__c, Submitted_To_Name__c,Avg_Weightage__c from Trifecta_Survey_Submission__c where id =:submissionId];
            avgWeightage = submission.Avg_Weightage__c;
            Survey_Global_Settings__c settings = [select Site_Address__c,Login_URL__c from Survey_Global_Settings__c][0];
            String siteURL = settings.Site_Address__c;
            String loginURL = settings.Login_URL__c;
            if (submission.Submitted_To__c != null) {
                if (submission.Submitted_To__c.subString(0,3) == schema.getGlobalDescribe().get('User').getDescribe().getKeyPrefix()) {
                    SurveyURL = loginURL+'apex/TTISGDisplayForm?Id='+submissionId+'&Survey='+getSurveyId(submissionId);
                } else if (submission.Submitted_To__c.subString(0,3) == schema.getGlobalDescribe().get('Contact').getDescribe().getKeyPrefix()) {
                    SurveyURL = siteURL+'TTISGDisplayForm?Id='+submissionId+'&Survey='+getSurveyId(submissionId);
                }
                return submission.Submitted_To_Name__c;
            }
            return null;
        }
        set;
    }
    public String getDetailUrl(){
        String loginURL = [select Login_URL__c from Survey_Global_Settings__c][0].Login_URL__c;
        return loginURL+submissionId;
    }
    public String getSurveyName() {
        Trifecta_Survey__c currentSurvey = [Select Name, Avg_Weightage__c from Trifecta_Survey__c where Id =:getSurveyId(submissionId)];
        return currentSurvey.Name;
    }
    private Id getSurveyId(Id submissionId) {
        return [Select Survey__c from Trifecta_Survey_Submission__c Where Id =:submissionId][0].Survey__c;
    }
}