src/objects/Survey_Global_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>setting for public site URL</description>
    <fields>
        <fullName>Site_Address__c</fullName>
        <label>Site Address</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Survey Global Settings</label>
</CustomObject>

src/objects/Trifecta_Survey__c.object
<CustomObject>
    <label>Trifecta Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trifecta Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Trifecta_Survey_Question__c.object
<CustomObject>
    <fields>
        <fullName>Load_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>External Unique value for every Survey Question record created.</description>
        <externalId>true</externalId>
        <label>Load Id</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Trifecta_Survey__c</referenceTo>
        <relationshipLabel>Trifecta Survey Questions</relationshipLabel>
        <relationshipName>Trifecta_Survey_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of the question ex: Text, Multi Select or Checkbox</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Multi Choice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Trifecta Survey Question</label>
    <nameField>
        <displayFormat>SQ-{000000}</displayFormat>
        <label>Trifecta Survey Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trifecta Survey Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Trifecta_Survey_Question_Choice__c.object
<CustomObject>
    <description>choices for the survey Question</description>
    <fields>
        <fullName>Load_Id__c</fullName>
        <description>External Unique value for every Survey Question Choice record created.</description>
        <externalId>true</externalId>
        <label>Load Id</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Question__c</fullName>
        <description>Id of the Survey Question</description>
        <label>Survey Question</label>
        <referenceTo>Trifecta_Survey_Question__c</referenceTo>
        <relationshipLabel>Trifecta Survey Question Choices</relationshipLabel>
        <relationshipName>Trifecta_Survey_Question_Choices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>text for the choice</description>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Trifecta Survey Question Choice</label>
    <nameField>
        <displayFormat>SQC-{0000000}</displayFormat>
        <label>Trifecta Survey Question Choice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trifecta Survey Question Choices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Trifecta_Survey_Question_Response__c.object
<CustomObject>
    <fields>
        <fullName>Answer__c</fullName>
        <description>Choice selected by the User/Contact</description>
        <label>Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Question__c</fullName>
        <description>Id of the Survey Question in current context</description>
        <label>Survey Question</label>
        <referenceTo>Trifecta_Survey_Question__c</referenceTo>
        <relationshipLabel>Trifecta Survey Question Responses</relationshipLabel>
        <relationshipName>Trifecta_Survey_Question_Responses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey_Submission__c</fullName>
        <description>Id of the Survey Submission</description>
        <label>Survey Submission</label>
        <referenceTo>Trifecta_Survey_Submission__c</referenceTo>
        <relationshipLabel>Trifecta Survey Question Responses</relationshipLabel>
        <relationshipName>Trifecta_Survey_Question_Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Trifecta Survey Question Response</label>
    <nameField>
        <displayFormat>SQR-{000000}</displayFormat>
        <label>Trifecta Survey Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trifecta Survey Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Trifecta_Survey_Submission__c.object
<CustomObject>
    <description>Junction object to link up Survey and User/Contact to whom the survey is submitted.</description>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to identify whether the feedback is submitted by the user or not.</description>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Submitted_To__c</fullName>
        <description>Id of User/Contact</description>
        <label>Submitted To</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Trifecta Survey Submission</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Trifecta Survey Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trifecta Survey Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TTISGDisplayFormController.cls
public with sharing class TTISGDisplayFormController {
    public String surveyId;
    public String submissionId;
    
    public TTISGSurveyService surveyService;
    public Boolean isSubmittedAlready {get; set;}
    
    public static final String USER_CONFIRMATION_PAGE_URL = '/apex/TTISGConfirmation?id=';
    public static final String CONTACT_CONFIRMATION_PAGE_URL = Survey_Global_Settings__c.getOrgDefaults().Site_Address__c+'TTISGConfirmation?id=';
    
    public Trifecta_Survey__c survey {get; set;}
    public List<Trifecta_Survey_Question__c> surveyQuestions {get; set;}
    public Map<String,List<Trifecta_Survey_Question_Choice__c>> surveyQuestionChoices{get; set;}
    
    public List<Trifecta_Survey_Question_Response__c> surveyResponses {get; set;}
    
    public Map<String,List<SelectOption>> questionChoices {get; set;}
    
    public Map<String,String> surveyQuestionChoiceMap{get;set;} 
    public Map<String,List<String>> checkboxChoiceMap {get; set;}
    public Trifecta_Survey_Submission__c surveySubmitted {get; set;}

    public TTISGDisplayFormController() {
        surveyId = ApexPages.currentPage().getParameters().get('Survey');
        submissionId = ApexPages.currentPage().getParameters().get('Id');
        
        if( surveyId != null && submissionId != null ) {
            surveyService = new TTISGSurveyService();
            surveyResponses = new List<Trifecta_Survey_Question_Response__c>(); 
            surveySubmitted = [select Id, Submitted_To__c, Completed__c from Trifecta_Survey_Submission__c where Id =:submissionId];
            
            if ([select Completed__c from Trifecta_Survey_Submission__c where Id=:submissionId].Completed__c ) {
                isSubmittedAlready = true;
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Sorry, this survey form has been submitted already.'));
            } else {
                survey  = surveyService.getSurveyById(surveyId);
                surveyQuestions = survey.Trifecta_Survey_Questions__r;
                surveyQuestionChoices = surveyService.getChoicesPerQuestion(TTISGSObjectUtils.pluckIds(surveyQuestions, 'Id'));  
                loadResponseMaps();
            }    
        } else {
            isSubmittedAlready = true;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Invalid URL'));    
        }
        
    }
    
    private void loadResponseMaps () {
    
        surveyQuestionChoiceMap = new Map<String,String>();
        checkboxChoiceMap = new Map<String, List<String>>();
        questionChoices = new Map<String,List<SelectOption>>();
        
        for (Trifecta_Survey_Question__c eachQuestion : surveyQuestions) {
            List<SelectOption> tempOptions = new List<SelectOption>();
            if (surveyQuestionChoices.size() != 0 && eachQuestion.Type__c != 'Text' ) {
                for(Trifecta_Survey_Question_Choice__c eachChoice : surveyQuestionChoices.get(eachQuestion.Load_Id__c)){
                    tempOptions.add(new SelectOption(eachChoice.Value__c,eachChoice.Value__c));
                }
                questionChoices.put(eachQuestion.Load_Id__c, tempOptions);
            }
            if (eachQuestion.Type__c == 'Checkbox') {
                checkboxChoiceMap.put(eachQuestion.Load_Id__c,new List<String>());
            }
            else {
                surveyQuestionChoiceMap.put(eachQuestion.Load_Id__c,'');
            }
        }
    }
    
    public PageReference submitSurvey(){
        //Save the survey before the user can be redirected to Send Survey Page
        Trifecta_Survey_Submission__c surveySubmitted = [select id, Submitted_To__c, Completed__c from Trifecta_Survey_Submission__c where Id =:submissionId];
        if(surveySubmitted != null && !surveySubmitted.Completed__c) {
            saveResponses();

            //Change the surveySubmission status to 'completed'
            surveySubmitted.Completed__c = true;
            upsert surveySubmitted;
            PageReference confirmationPage;
            if (TTISGSurveyUtils.isValidId(surveySubmitted.Submitted_To__c, 'User')) {
                confirmationPage = new PageReference(TTISGDisplayFormController.USER_CONFIRMATION_PAGE_URL+submissionId);
            } else {
                confirmationPage = new PageReference(TTISGDisplayFormController.CONTACT_CONFIRMATION_PAGE_URL+submissionId);
            }
            confirmationPage.setRedirect(true);
            return confirmationPage;
        } else {
             isSubmittedAlready = true;
             ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'This survey form has been submitted already.'));
             return null;
        }        
    }   

    private void saveResponses() {
        surveyResponses = new List<Trifecta_Survey_Question_Response__c>();
        Trifecta_Survey_Question_Response__c surveyResponse = new Trifecta_Survey_Question_Response__c();
        
        for (Trifecta_Survey_Question__c eachQuestion: surveyQuestions) {
            surveyResponse = new Trifecta_Survey_Question_Response__c(Survey_Submission__c=submissionId, 
                                Survey_Question__c = eachQuestion.Id);
            if (eachQuestion.Type__c == 'Checkbox') {
                //for checkbox type questions, choices will be returned as List<String> from UI
                surveyResponse.Answer__c = String.join(checkboxChoiceMap.get(eachQuestion.Load_Id__c), ','); 
            } else {
                surveyResponse.Answer__c = surveyQuestionChoiceMap.get(eachQuestion.Load_Id__c);
            }
            surveyResponses.add(surveyResponse);
        }
        insert surveyResponses;
        
        //Task eachTask = [SELECT Id, WhatId, Status FROM Task WHERE WhatId = :submissionId];
        //if (eachTask != null) {
        //  eachTask.Status = 'Completed';
        //upsert eachTask;
        //}
    }
    public Boolean getUser() {
        return TTISGSurveyUtils.isValidId(surveySubmitted.Submitted_To__c, 'User');
    }
}