src/objects/Trifecta_Survey__c.object
<CustomObject>
    <fields>
        <fullName>Auto_Response_Message__c</fullName>
        <description>Message to be displayed after the submission of the survey</description>
        <label>Auto Response Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Trifecta Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trifecta Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Trifecta_Survey_Submission__c.object
<CustomObject>
    <description>Junction object to link up Survey and User/Contact to whom the survey is submitted.</description>
    <fields>
        <fullName>Submitted_To__c</fullName>
        <description>Id of User/Contact</description>
        <label>Submitted To</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <description>Survey which is submitted</description>
        <label>Survey</label>
        <referenceTo>Trifecta_Survey__c</referenceTo>
        <relationshipLabel>Trifecta Survey Submissions</relationshipLabel>
        <relationshipName>Trifecta_Survey_Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Trifecta Survey Submission</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Trifecta Survey Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trifecta Survey Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TTISGConfirmationPageController.cls
public with sharing class TTISGConfirmationPageController {
    public String submissionId {get; set;}
    public String surveyId {get; set;}
    public String submitterId {get; set;}
    public String confirmationMessage{get; set;}
    
    public TTISGConfirmationPageController () {
        submissionId = ApexPages.currentPage().getParameters().get('Id');
        getSurveyDetails(submissionId.trim());
        confirmationMessage= [select Auto_Response_Message__c from Trifecta_Survey__c where Id =:surveyId].Auto_Response_Message__c;
    }
    private void getSurveyDetails(Id submissionId) {
        Trifecta_Survey_Submission__c surveyRecord = [Select Survey__c, Submitted_To__c from Trifecta_Survey_Submission__c Where Id =:submissionId];
        submitterId = surveyRecord.Submitted_To__c;
        surveyId = surveyRecord.Survey__c;
    }
}