src/objects/Trifecta_Survey__c.object
<CustomObject>
    <label>Trifecta Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trifecta Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Trifecta_Survey_Question__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of the question ex: Text, Multi Select or Checkbox</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Multi Choice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Trifecta Survey Question</label>
    <nameField>
        <displayFormat>SQ-{000000}</displayFormat>
        <label>Trifecta Survey Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trifecta Survey Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Trifecta_Survey_Question_Choice__c.object
<CustomObject>
    <description>choices for the survey Question</description>
    <fields>
        <fullName>Survey_Question__c</fullName>
        <description>Id of the Survey Question</description>
        <label>Survey Question</label>
        <referenceTo>Trifecta_Survey_Question__c</referenceTo>
        <relationshipLabel>Trifecta Survey Question Choices</relationshipLabel>
        <relationshipName>Trifecta_Survey_Question_Choices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>text for the choice</description>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Trifecta Survey Question Choice</label>
    <nameField>
        <displayFormat>SQC-{0000000}</displayFormat>
        <label>Trifecta Survey Question Choice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trifecta Survey Question Choices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Trifecta_Survey_Question_Response__c.object
<CustomObject>
    <fields>
        <fullName>Answer__c</fullName>
        <description>Choice selected by the User/Contact</description>
        <label>Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Question__c</fullName>
        <description>Id of the Survey Question in current context</description>
        <label>Survey Question</label>
        <referenceTo>Trifecta_Survey_Question__c</referenceTo>
        <relationshipLabel>Trifecta Survey Question Responses</relationshipLabel>
        <relationshipName>Trifecta_Survey_Question_Responses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Trifecta Survey Question Response</label>
    <nameField>
        <displayFormat>SQR-{000000}</displayFormat>
        <label>Trifecta Survey Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trifecta Survey Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Trifecta_Survey_Submission__c.object
<CustomObject>
    <description>Junction object to link up Survey and User/Contact to whom the survey is submitted.</description>
    <label>Trifecta Survey Submission</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Trifecta Survey Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trifecta Survey Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TTISGTestObjectTriggers.cls
@isTest(seeAllData=false)
public with sharing class TTISGTestObjectTriggers {
    @testSetup
    static void createTestData() {
        // Creating Test Survey , Survey Questions , Survey Question Choices
        Trifecta_Survey__c survey = TTISGTestUtils.createSurvey('Sample Survey');
        List<Trifecta_Survey_Question__c> surveyQuestions = TTISGTestUtils.createSurveyQuestions(survey.Id);
        List<Id> surveyQuestionIds = TTISGSObjectUtils.pluckIds(surveyQuestions,'Id');
        TTISGTestUtils.createSurveyChoices(surveyQuestionIds);
    }

    @isTest    // Verifying the Updation of submitted response stopped by the non-eligible user
    static void testRecordUpdations() {
        // Querying up profiles required for the users below
        Profile platformprofile = [SELECT Id FROM Profile WHERE Name='Standard Platform User'];
        Profile systemadminprofile = [SELECT Id FROM Profile WHERE Name='System Administrator']; 

        // Constructing required test users
        User u2 = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                            LocaleSidKey='en_US', ProfileId = systemadminprofile.Id, 
                            TimeZoneSidKey='America/Los_Angeles', UserName='surveymakeradminuser@testorg.com');  
        User u1;

        // Querying required permission which is to be assigned to non admin user
        PermissionSet pset = [Select Id,Name from PermissionSet Where Name = 'Survey_Maker_Permissions'];

        System.runAs(u2) {
            // Inserting PermissionSetAssignment and Non Admin user record as co-admin User to avoid Mixed DML Error
            u1 = new User(Alias = 'standt', Email='standarduser@testorg.com',FirstName='Admin', 
                            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                            LocaleSidKey='en_US', ProfileId = platformprofile.Id, 
                            TimeZoneSidKey='America/Los_Angeles', UserName='surveymakertestuser@testorg.com');
            insert u1;
            
            PermissionSetAssignment passign = new PermissionSetAssignment();
            passign.AssigneeId = u1.Id;
            passign.PermissionSetId = pset.Id;
            insert passign;
        }
        
        // Coming back to current user content , creating a Submission for the Survey
        Trifecta_Survey__c survey = [Select Id,Name from Trifecta_Survey__c LIMIT 1];
        Trifecta_Survey_Submission__c submission =  TTISGTestUtils.createSubmission(survey.Id, u1.Id,'Admin Testing',false);

        

        System.runAs(u1) {  
            Trifecta_Survey_Question_Response__c response1,response2,response3;
            
            List<Trifecta_Survey_Question__c> qList = [Select Id,Name from Trifecta_Survey_Question__c ORDER BY Type__c];

            // Creating responses as Non Admin User but not current User
            response1 = TTISGTestUtils.createResponseForQuestion(submission.Id,qList[1].Id,'RadioButtonOption1');
            response2 = TTISGTestUtils.createResponseForQuestion(submission.Id,qList[0].Id,'CheckBoxOption1;CheckBoxOption2');
            response3 = TTISGTestUtils.createResponseForQuestion(submission.Id,qList[2].Id,'Sample Answert');
            
            List<Trifecta_Survey_Question_Response__c> responsesList = new List<Trifecta_Survey_Question_Response__c>{response1,response2,response3};
            insert responsesList;

            Boolean cameToException=false;
            String exceptionMessage;
            try{
                response1.Answer__c = 'RadioButtonOption2'; // If Response giving user try to edit the Response
                update response1;
            } 
            catch(Exception e) {
                cameToException = true;
                exceptionMessage = e.getMessage();
            }
            System.assertEquals(true,cameToException,'Failed Asserting that the unintended User Got Error Message , Updating His Reponse');
            System.assertEquals(true,exceptionMessage.contains('You Do Not Have Permissions to Modify the Record'),'Failed Asserting Error Message');
        } 
    }   

    @isTest    // Verifying the Deletions (Question , Choice , Submission , Survey) are working stopped by the non-eligible user
    static void testRecordDeletions() {
        // Querying up profiles required for the users below
        Profile platformprofile = [SELECT Id FROM Profile WHERE Name='Standard Platform User'];
        Profile systemadminprofile = [SELECT Id FROM Profile WHERE Name='System Administrator']; 

        // Constructing required test users
        User u2 = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                            LocaleSidKey='en_US', ProfileId = systemadminprofile.Id, 
                            TimeZoneSidKey='America/Los_Angeles', UserName='surveymakeradminuser@testorg.com');  
        User u1;

        // Querying required permission which is to be assigned to non admin user
        PermissionSet pset = [Select Id,Name from PermissionSet Where Name = 'Survey_Maker_Permissions'];

        System.runAs(u2) {
            // Inserting PermissionSetAssignment and Non Admin user record as co-admin User to avoid Mixed DML Error
            u1 = new User(Alias = 'standt', Email='standarduser@testorg.com',FirstName='Admin', 
                            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                            LocaleSidKey='en_US', ProfileId = platformprofile.Id, 
                            TimeZoneSidKey='America/Los_Angeles', UserName='surveymakertestuser@testorg.com');
            insert u1;
            
            PermissionSetAssignment passign = new PermissionSetAssignment();
            passign.AssigneeId = u1.Id;
            passign.PermissionSetId = pset.Id;
            insert passign;
        }
        
        // Coming back to current user content , creating a Submission for the Survey
        Trifecta_Survey__c survey = [Select Id,Name from Trifecta_Survey__c LIMIT 1];
        Trifecta_Survey_Submission__c submission =  TTISGTestUtils.createSubmission(survey.Id, u1.Id,'Admin Testing',false);

        Boolean cameToException=false;
        String exceptionMessage;
        
        System.runAs(u1) {  
            Trifecta_Survey_Question_Response__c response1,response2,response3;
            
            List<Trifecta_Survey_Question__c> qList = [Select Id,Name from Trifecta_Survey_Question__c ORDER BY Type__c];

            // Creating responses as Non Admin User but not current User
            response1 = TTISGTestUtils.createResponseForQuestion(submission.Id,qList[1].Id,'RadioButtonOption1');
            response2 = TTISGTestUtils.createResponseForQuestion(submission.Id,qList[0].Id,'CheckBoxOption1;CheckBoxOption2');
            response3 = TTISGTestUtils.createResponseForQuestion(submission.Id,qList[2].Id,'Sample Answert');
            
            List<Trifecta_Survey_Question_Response__c> responsesList = new List<Trifecta_Survey_Question_Response__c>{response1,response2,response3};
            insert responsesList;

            try {
                delete submission;     // Trying to delete the Submission which the user is not intended to be doing so
            }
            catch(Exception e){
                cameToException = true;
                exceptionMessage = e.getMessage();
            }
            System.assertEquals(true,cameToException,'Failed Asserting that the unintended User Got Error Message, Deleting Submission created by Submitter');
            System.assertEquals(true,exceptionMessage.contains('You Do Not Have Permissions to Delete the Record'),'Failed Asserting Error Message');

            try {
                delete qList;       // Trying to delete the Questions which the user is not intended to be doing so
            }
            catch(Exception e){
                cameToException = true;
                exceptionMessage = e.getMessage();
            }
            System.assertEquals(true,cameToException,'Failed Asserting that the unintended User Got Error Message , Deleting Questions created by Submitter');
            System.assertEquals(true,exceptionMessage.contains('You Do Not Have Permissions to Delete the Record'),'Failed Asserting Error Message');

            List<Trifecta_Survey_Question_Choice__c> questionChoices = [Select Id,Name,Value__c from Trifecta_Survey_Question_Choice__c Where Survey_Question__r.Type__c = 'Radio Button'];

            try {
                delete questionChoices;       // Trying to delete the Radio Button Question Choices which the user is not intended to be doing so
            }
            catch(Exception e){
                cameToException = true;
                exceptionMessage = e.getMessage();
            }
            System.assertEquals(true,cameToException,'Failed Asserting that the unintended User Got Error Message , Deleting the Question Choices created by Submitter');
            System.assertEquals(true,exceptionMessage.contains('You Do Not Have Permissions to Delete the Record'),'Failed Asserting Error Message');


            try {
                delete survey;       // Trying to delete the Survey which the user is not intended to be doing so
            }
            catch(Exception e){
                cameToException = true;
                exceptionMessage = e.getMessage();
            }
            System.assertEquals(true,cameToException,'Failed Asserting that the unintended User Got Error Message , Deleting the Survey itself');
            // Asserting that error message because trying to delete a master record to which he is not the owner nor on top of main user in role hierarchy
            System.assertEquals(true,exceptionMessage.contains('INSUFFICIENT_ACCESS_OR_READONLY'),'Failed Asserting Error Message');

        }

        // Running as Co Admin and trying to delet the Survey
        System.runAs(u2) {
            try {
                delete survey;       // Trying to delete the Survey which the Co Admin user is not intended to be doing so
            }
            catch(Exception e){
                cameToException = true;
                exceptionMessage = e.getMessage();
            }
            System.assertEquals(true,cameToException,'Failed Asserting that the Co Admin User Got Error Message , Deleting the Survey');
            System.assertEquals(true,exceptionMessage.contains('You Do Not Have Permissions to Delete the Record'),'Failed Asserting Error Message');
        }

    }

    @isTest // Verifying the Deletions (Question , Choice , Submission , Survey) are working good by the right eligible user
    static void testDeletionByRightUser() {
        List<Trifecta_Survey_Question_Choice__c> questionChoices = [Select Id,Name,Value__c from Trifecta_Survey_Question_Choice__c Where Survey_Question__r.Type__c = 'Radio Button'];

        Boolean cameToException=false;
        String exceptionMessage;

        try {
            delete questionChoices;       // Trying to delete the Radio Button Question Choices 
        }
        catch(Exception e){
            cameToException = true;
            exceptionMessage = e.getMessage();
        }
        System.assertEquals(false,cameToException,'Failed Asserting that the unintended User Got Error Message , Deleting the Question Choices created by Submitter');
        System.assertEquals(null,exceptionMessage,'Failed Asserting Error Message');
        System.assertEquals(0,[Select Count() from Trifecta_Survey_Question_Choice__c Where Survey_Question__r.Type__c = 'Radio Button']);
        // Successfull deletion of Survey Radio Button Question Choices

        // Preparing the Submission Object
        Profile platformprofile = [SELECT Id FROM Profile WHERE Name='Standard Platform User'];
        Profile systemadminprofile = [SELECT Id FROM Profile WHERE Name='System Administrator']; 

        // Constructing required test users
        User u2 = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                            LocaleSidKey='en_US', ProfileId = systemadminprofile.Id, 
                            TimeZoneSidKey='America/Los_Angeles', UserName='surveymakeradminuser@testorg.com');  
        User u1;

        // Querying required permission which is to be assigned to non admin user
        PermissionSet pset = [Select Id,Name from PermissionSet Where Name = 'Survey_Maker_Permissions'];

        System.runAs(u2) {
            // Inserting PermissionSetAssignment and Non Admin user record as co-admin User to avoid Mixed DML Error
            u1 = new User(Alias = 'standt', Email='standarduser@testorg.com',FirstName='Admin', 
                            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                            LocaleSidKey='en_US', ProfileId = platformprofile.Id, 
                            TimeZoneSidKey='America/Los_Angeles', UserName='surveymakertestuser@testorg.com');
            insert u1;
            
            PermissionSetAssignment passign = new PermissionSetAssignment();
            passign.AssigneeId = u1.Id;
            passign.PermissionSetId = pset.Id;
            insert passign;
        }
        
        // Coming back to current user content , creating a Submission for the Survey
        Trifecta_Survey__c survey = [Select Id,Name from Trifecta_Survey__c LIMIT 1];
        Trifecta_Survey_Submission__c submission =  TTISGTestUtils.createSubmission(survey.Id, u1.Id,'Admin Testing',false);
        
        try {
            delete submission;     // Trying to delete the Submission 
        }
        catch(Exception e){
            cameToException = true;
            exceptionMessage = e.getMessage(); 
        }
        System.assertEquals(false,cameToException,'Failed Asserting that the unintended User Got Error Message , Deleting the Survey Submission');
        System.assertEquals(null,exceptionMessage,'Failed Asserting Error Message');
        System.assertEquals(0,[Select Count() from Trifecta_Survey_Submission__c]);

        List<Trifecta_Survey_Question__c> qList = [Select Id,Name from Trifecta_Survey_Question__c ORDER BY Type__c];

        try {
            delete qList;       // Trying to delete the Questions
        }
        catch(Exception e){
            cameToException = true;
            exceptionMessage = e.getMessage();
        }
        System.assertEquals(false,cameToException,'Failed Asserting that the unintended User Got Error Message , Deleting Questions created by Submitter');
        System.assertEquals(null,exceptionMessage,'Failed Asserting Error Message');
        System.assertEquals(0,[Select Count() from Trifecta_Survey_Question__c]);

        try {
            delete survey;       // Trying to delete the Survey
        }
        catch(Exception e){
            cameToException = true;
            exceptionMessage = e.getMessage();
        }
        System.assertEquals(false,cameToException,'Failed Asserting that the Co Admin User Got Error Message , Deleting the Survey');
        System.assertEquals(null,exceptionMessage,'Failed Asserting Error Message');
        System.assertEquals(0,[Select Count() from Trifecta_Survey__c]);
    }
}