src/objects/Trifecta_Survey__c.object
<CustomObject>
    <fields>
        <fullName>Auto_Response_Message__c</fullName>
        <description>Message to be displayed after the submission of the survey</description>
        <label>Auto Response Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the survey</description>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Help_Text__c</fullName>
        <description>Inline help text for the purpose of the survey</description>
        <label>Help Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Trifecta Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trifecta Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Trifecta_Survey_Question__c.object
<CustomObject>
    <fields>
        <fullName>Help_text__c</fullName>
        <description>Help text to explain the user about the sample response to be filled.</description>
        <label>Help text</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Load_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>External Unique value for every Survey Question record created.</description>
        <externalId>true</externalId>
        <label>Load Id</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sort_Index__c</fullName>
        <description>Number to arrange the question in the survey form generated</description>
        <label>Sort Index</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Trifecta_Survey__c</referenceTo>
        <relationshipLabel>Trifecta Survey Questions</relationshipLabel>
        <relationshipName>Trifecta_Survey_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Title of the question</description>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of the question ex: Text, Multi Select or Checkbox</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Multi Choice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>isRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to mark this as a required question</description>
        <label>isRequired</label>
        <type>Checkbox</type>
    </fields>
    <label>Trifecta Survey Question</label>
    <nameField>
        <displayFormat>SQ-{000000}</displayFormat>
        <label>Trifecta Survey Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trifecta Survey Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Trifecta_Survey_Question_Choice__c.object
<CustomObject>
    <description>choices for the survey Question</description>
    <fields>
        <fullName>Load_Id__c</fullName>
        <description>External Unique value for every Survey Question Choice record created.</description>
        <externalId>true</externalId>
        <label>Load Id</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Question__c</fullName>
        <description>Id of the Survey Question</description>
        <label>Survey Question</label>
        <referenceTo>Trifecta_Survey_Question__c</referenceTo>
        <relationshipLabel>Trifecta Survey Question Choices</relationshipLabel>
        <relationshipName>Trifecta_Survey_Question_Choices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>text for the choice</description>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Weightage__c</fullName>
        <description>Used to track the weightage of the choice when populating the chart.</description>
        <inlineHelpText>Add weightage if you would like to display them in chart.</inlineHelpText>
        <label>Weightage</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Trifecta Survey Question Choice</label>
    <nameField>
        <displayFormat>SQC-{0000000}</displayFormat>
        <label>Trifecta Survey Question Choice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trifecta Survey Question Choices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TTISGSurveyService.cls
public with sharing class TTISGSurveyService {
    public TTISGSurveyService() {
        
    }

    public Trifecta_Survey__c getSurveyById(String id) {
        List<String> surveyFields = TTISGSoqlUtils.star('Trifecta_Survey__c');
        surveyFields.add('('+TTISGSoqlUtils.getSelect(TTISGSoqlUtils.star('Trifecta_Survey_Question__c'), 'Trifecta_Survey_Questions__r').withOrder(TTISGSoqlUtils.getOrder('Sort_Index__c')).toString()+')');
        TTISGSoqlUtils.Soqlquery query = TTISGSoqlUtils.getSelect(surveyFields,'Trifecta_Survey__c')
                                                .withCondition(TTISGSoqlUtils.getEq('Id',id));

        return Database.query(query.toString());
    }

    public Map<String, List<Trifecta_Survey_Question_Choice__c>> getChoicesPerQuestion(List<String> questionIds) {

        List<String> surveyQuestionFields = TTISGSoqlUtils.star('Trifecta_Survey_Question__c');

        List<String> surveyQuestionChoiceFields = TTISGSoqlUtils.star('Trifecta_Survey_Question_Choice__c');
        surveyQuestionFields.add('('+TTISGSoqlUtils.getSelect(surveyQuestionChoiceFields, 'Trifecta_Survey_Question_Choices__r').withOrder(TTISGSoqlUtils.getOrder('Sort_Index__c')).toString()+')');
        TTISGSoqlUtils.Soqlquery soqlQuery = TTISGSoqlUtils.getSelect(surveyQuestionFields,'Trifecta_Survey_Question__c').withCondition(TTISGSoqlUtils.getIn('Id',questionIds));

        Map<String, List<Trifecta_Survey_Question_Choice__c>> choicesPerQuestion = new Map<String, List<Trifecta_Survey_Question_Choice__c>>();
        for(Trifecta_Survey_Question__c q: Database.query(soqlQuery.toString())) {
            if (q.Type__c == 'Text' ) {
                choicesPerQuestion.put(q.Load_Id__c, new List<Trifecta_Survey_Question_Choice__c>());
            } else {
               choicesPerQuestion.put(q.Load_Id__c, q.Trifecta_Survey_Question_Choices__r);
            }
        }
        return choicesPerQuestion;
    }

    public void retainQuestionsAndChoicesDeleteAllOthers(Id surveyId,List<Id> qIds,List<Id> chIds) {
        List<Trifecta_Survey_Question__c> questionsToDelete = [Select Id,Name from Trifecta_Survey_Question__c Where ID NOT IN : qIds AND Survey__c =:surveyId];
        List<Trifecta_Survey_Question_Choice__c> choicesToDelete = [Select Id,Name from Trifecta_Survey_Question_Choice__c Where ID NOT IN : chIds AND Survey_Question__r.Survey__c =:surveyId];
      
        if(questionsToDelete.size() > 0) {
           delete questionsToDelete;
        }
        if(choicesToDelete.size() > 0) {
           Database.delete(choicesToDelete,false);
        }
    }

    public Trifecta_Survey_Question_Choice__c cloneChoice(Trifecta_Survey_Question_Choice__c original) {
        return new Trifecta_Survey_Question_Choice__c(Load_Id__c = TTISGGuidUtil.NewGuid(),
                                                        Value__c = original.Value__c,
                                                        Weightage__c = original.Weightage__c);
    }

    public Trifecta_Survey_Question__c cloneQuestion(Trifecta_Survey_Question__c original) {
        return new Trifecta_Survey_Question__c(Load_Id__c = TTISGGuidUtil.NewGuid(),
                                                    Help_text__c = original.Help_text__c,
                                                    Sort_Index__c = original.Sort_Index__c,
                                                    Title__c = original.Title__c,
                                                    Type__c = original.Type__c,
                                                    isEdit__c = original.isEdit__c,
                                                    isRequired__c = original.isRequired__c);
    }

    public Id cloneSurvey(Id surveyId) {
        Trifecta_Survey__c oldSurvey = getSurveyById(surveyId);

        List<String> oldQuestionIds = new List<String>();
        for (Trifecta_Survey_Question__c eachQuestion : oldSurvey.Trifecta_Survey_Questions__r) {
            oldQuestionIds.add(eachQuestion.id);
        }
        Map<String, List<Trifecta_Survey_Question_Choice__c>> oldChoices = getChoicesPerQuestion(oldQuestionIds);

        // creating new survey
        Trifecta_Survey__c newSurvey = new Trifecta_Survey__c(Name=oldSurvey.Name,
                                                            Auto_Response_Message__c = oldSurvey.Auto_Response_Message__c,
                                                            Description__c = oldSurvey.Description__c,
                                                            Help_Text__c = oldSurvey.Help_Text__c,
                                                            Load_Id__c = TTISGGuidUtil.NewGuid(),
                                                            Threshold_Weightage__c = oldSurvey.Threshold_Weightage__c);
        insert newSurvey;
        
        // creating new question with choices 
        List<Trifecta_Survey_Question__c> childQuestions = new List<Trifecta_Survey_Question__c>();
        List<Trifecta_Survey_Question_Choice__c> childChoices = new List<Trifecta_Survey_Question_Choice__c>();
        for (Trifecta_Survey_Question__c eachQuestion : oldSurvey.Trifecta_Survey_Questions__r) {
            Trifecta_Survey_Question__c newChildQuestion = cloneQuestion(eachQuestion);
            newChildQuestion.Survey__c = newSurvey.Id;
            for (Trifecta_Survey_Question_Choice__c eachChoice : oldChoices.get(eachQuestion.Load_Id__c)) {
                Trifecta_Survey_Question_Choice__c newChoice = cloneChoice(eachChoice);
                newChoice.Survey_Question__r = new Trifecta_Survey_Question__c(Load_Id__c = newChildQuestion.Load_Id__c );
                childChoices.add(newChoice);
            }            
            childQuestions.add(newChildQuestion);
        }
        insert childQuestions;
        insert childChoices;
                
        return newSurvey.Id;

    }
}