src/objects/Trifecta_Survey_Submission__c.object
<CustomObject>
    <description>Junction object to link up Survey and User/Contact to whom the survey is submitted.</description>
    <fields>
        <fullName>Survey__c</fullName>
        <description>Survey which is submitted</description>
        <label>Survey</label>
        <referenceTo>Trifecta_Survey__c</referenceTo>
        <relationshipLabel>Trifecta Survey Submissions</relationshipLabel>
        <relationshipName>Trifecta_Survey_Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Trifecta Survey Submission</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Trifecta Survey Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trifecta Survey Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SendEmailComponentController.cls
public with sharing class SendEmailComponentController {
    public Id submissionId { get; set; }
    public Id senderId { get; set; }
    public String getSurveyURL() {
    	return 'https://login.salesforce.com/apex/displayForm?Id='+submissionId+'&Survey='+getSurveyId(submissionId);
    }
    private Id getSurveyId(Id submissionId) {
    	return [Select Survey__c from Trifecta_Survey_Submission__c Where Id =:submissionId][0].Survey__c;
    }
}