src/objects/Trifecta_Survey__c.object
<CustomObject>
    <fields>
        <fullName>Auto_Response_Message__c</fullName>
        <description>Message to be displayed after the submission of the survey</description>
        <label>Auto Response Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Help_Text__c</fullName>
        <description>Inline help text for the purpose of the survey</description>
        <label>Help Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Trifecta Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trifecta Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Trifecta_Survey_Question__c.object
<CustomObject>
    <fields>
        <fullName>Help_text__c</fullName>
        <description>Help text to explain the user about the sample response to be filled.</description>
        <label>Help text</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Load_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>External Unique value for every Survey Question record created.</description>
        <externalId>true</externalId>
        <label>Load Id</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Trifecta_Survey__c</referenceTo>
        <relationshipLabel>Trifecta Survey Questions</relationshipLabel>
        <relationshipName>Trifecta_Survey_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Title of the question</description>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of the question ex: Text, Multi Select or Checkbox</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Multi Choice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>isRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to mark this as a required question</description>
        <label>isRequired</label>
        <type>Checkbox</type>
    </fields>
    <label>Trifecta Survey Question</label>
    <nameField>
        <displayFormat>SQ-{000000}</displayFormat>
        <label>Trifecta Survey Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trifecta Survey Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Trifecta_Survey_Question_Choice__c.object
<CustomObject>
    <description>choices for the survey Question</description>
    <fields>
        <fullName>Load_Id__c</fullName>
        <description>External Unique value for every Survey Question Choice record created.</description>
        <externalId>true</externalId>
        <label>Load Id</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Question__c</fullName>
        <description>Id of the Survey Question</description>
        <label>Survey Question</label>
        <referenceTo>Trifecta_Survey_Question__c</referenceTo>
        <relationshipLabel>Trifecta Survey Question Choices</relationshipLabel>
        <relationshipName>Trifecta_Survey_Question_Choices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>text for the choice</description>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Weightage__c</fullName>
        <description>Used to track the weightage of the choice when populating the chart.</description>
        <inlineHelpText>Add weightage if you would like to display them in chart.</inlineHelpText>
        <label>Weightage</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Trifecta Survey Question Choice</label>
    <nameField>
        <displayFormat>SQC-{0000000}</displayFormat>
        <label>Trifecta Survey Question Choice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trifecta Survey Question Choices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Trifecta_Survey_Question_Response__c.object
<CustomObject>
    <fields>
        <fullName>Survey_Question__c</fullName>
        <description>Id of the Survey Question in current context</description>
        <label>Survey Question</label>
        <referenceTo>Trifecta_Survey_Question__c</referenceTo>
        <relationshipLabel>Trifecta Survey Question Responses</relationshipLabel>
        <relationshipName>Trifecta_Survey_Question_Responses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey_Submission__c</fullName>
        <description>Id of the Survey Submission</description>
        <label>Survey Submission</label>
        <referenceTo>Trifecta_Survey_Submission__c</referenceTo>
        <relationshipLabel>Trifecta Survey Question Responses</relationshipLabel>
        <relationshipName>Trifecta_Survey_Question_Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Trifecta Survey Question Response</label>
    <nameField>
        <displayFormat>SQR-{000000}</displayFormat>
        <label>Trifecta Survey Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trifecta Survey Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Trifecta_Survey_Submission__c.object
<CustomObject>
    <description>Junction object to link up Survey and User/Contact to whom the survey is submitted.</description>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to identify whether the feedback is submitted by the user or not.</description>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Submitted_To__c</fullName>
        <description>Id of User/Contact</description>
        <label>Submitted To</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <description>Survey which is submitted</description>
        <label>Survey</label>
        <referenceTo>Trifecta_Survey__c</referenceTo>
        <relationshipLabel>Trifecta Survey Submissions</relationshipLabel>
        <relationshipName>Trifecta_Survey_Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Trifecta Survey Submission</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Trifecta Survey Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trifecta Survey Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TTISGDisplayFormControllerTest.cls
@isTest
private class TTISGDisplayFormControllerTest {
	
	@isTest public static void validUserSubmission() {
	Trifecta_Survey__c survey = setData();
        
        Trifecta_Survey_Submission__c surveySubmission = [SELECT ID FROM Trifecta_Survey_Submission__c WHERE Survey__c = :survey.ID];
        
        Test.setCurrentPage(Page.TTISGDisplayForm);
        ApexPages.currentPage().getParameters().put('Survey',survey.Id);
        ApexPages.currentPage().getParameters().put('Id',surveySubmission.Id);
        
        TTISGDisplayFormController displayForm = new TTISGDisplayFormController();
        
        
        displayForm.submitSurvey();

        List<Trifecta_Survey_Question_Response__c> responseList = [SELECT Id FROM Trifecta_Survey_Question_Response__c WHERE Survey_Submission__c = :surveySubmission.Id];
        System.assertEquals(3, responseList.size(), 'no.of responses are not equal to questions');
        
        Boolean validUser = displayForm.getUser();

	}

	@isTest public static void validContactSubmission() {
	Trifecta_Survey__c survey = setData();
        Trifecta_Survey_Submission__c surveySubmission = [SELECT ID FROM Trifecta_Survey_Submission__c WHERE Survey__c = :survey.ID];

        Contact newContact = new Contact(LastName ='pavan kumar', Email ='test@test.com');
        insert newContact;

        surveySubmission.Submitted_To__c = newContact.Id;
        update surveySubmission;

        Test.setCurrentPage(Page.TTISGDisplayForm);
        ApexPages.currentPage().getParameters().put('Survey',survey.Id);
        ApexPages.currentPage().getParameters().put('Id',surveySubmission.Id);
        
        TTISGDisplayFormController displayForm = new TTISGDisplayFormController();
        displayForm.submitSurvey();

        List<Trifecta_Survey_Question_Response__c> responseList = [SELECT Id FROM Trifecta_Survey_Question_Response__c WHERE Survey_Submission__c = :surveySubmission.Id];
        System.assertEquals(3, responseList.size(), 'no.of responses are not equal to questions');
        
	}

	@isTest public static void invalidURLTest() {
	Trifecta_Survey__c survey = setData();
        Trifecta_Survey_Submission__c surveySubmission = [SELECT ID FROM Trifecta_Survey_Submission__c WHERE Survey__c = :survey.ID];
        Test.setCurrentPage(Page.TTISGDisplayForm);
        
        TTISGDisplayFormController displayForm = new TTISGDisplayFormController();

        System.assertEquals(true, ApexPages.hasMessages(), 'invalid URL');

	}

	@isTest public static void alreadySubmittedTest() {
	Trifecta_Survey__c survey = setData();
        Trifecta_Survey_Submission__c surveySubmission = [SELECT ID FROM Trifecta_Survey_Submission__c WHERE Survey__c = :survey.ID];
        surveySubmission.Completed__c = true;
        update surveySubmission;

        Test.setCurrentPage(Page.TTISGDisplayForm);
        ApexPages.currentPage().getParameters().put('Survey',survey.Id);
        ApexPages.currentPage().getParameters().put('Id',surveySubmission.Id);

        TTISGDisplayFormController displayForm = new TTISGDisplayFormController();
        displayForm.submitSurvey();

        System.assertEquals(true, ApexPages.hasMessages(), 'submiited already');


	}

	private static Trifecta_Survey__c setData() {
	
        Trifecta_Survey__c survey = new Trifecta_Survey__c(Name='new survey', Auto_Response_Message__c = 'thank you', 
        						Help_Text__c = 'survey help', Load_Id__c = TTISGGuidUtil.NewGuid(),
        						Threshold_Weightage__c = 0);
	insert survey;
	Trifecta_Survey_Question__c radioQuestion = new Trifecta_Survey_Question__c(Title__c = 'Radio Button question', 
										Type__c = TTISGSurveyUtils.QUESTION_TYPE_RADIO, isRequired__c = true, 
										Load_Id__c = TTISGGuidUtil.NewGuid(), 
										Help_text__c = 'Radio button question help text', Survey__c = survey.Id);
        Trifecta_Survey_Question__c checkQuestion = new Trifecta_Survey_Question__c(Title__c = 'Check Box question', 
										Type__c = 'Checkbox', isRequired__c = true, 
										Load_Id__c = TTISGGuidUtil.NewGuid(), 
										Help_text__c = 'Check Box question help text', Survey__c = survey.Id);
        Trifecta_Survey_Question__c textQuestion = new Trifecta_Survey_Question__c(Title__c = TTISGSurveyUtils.DEFAULT_QUESTION_TITLE, Type__c = 'Text', 
        									isRequired__c = true, Load_Id__c = TTISGGuidUtil.NewGuid(), 
        									Help_text__c = 'Text question help text', Survey__c = survey.Id);
        List<Trifecta_Survey_Question__c> questionList = new List<Trifecta_Survey_Question__c>();
        questionList.add(radioQuestion);
        questionList.add(checkQuestion);
        questionList.add(textQuestion);
        insert questionList;
        List<Trifecta_Survey_Question_Choice__c> choiceList = new List<Trifecta_Survey_Question_Choice__c>();
        Trifecta_Survey_Question_Choice__c radioButtonOption1 = new Trifecta_Survey_Question_Choice__c(Load_Id__c = TTISGGuidUtil.NewGuid(), 
        											Value__c = 'radioButtonOption1', 
        											Weightage__c = 2, Survey_Question__c = radioQuestion.Id );
        Trifecta_Survey_Question_Choice__c radioButtonOption2 = new Trifecta_Survey_Question_Choice__c(Load_Id__c = TTISGGuidUtil.NewGuid(), 
        											Value__c = 'radioButtonOption2', 
        											Weightage__c = 4, Survey_Question__c = radioQuestion.Id);
        Trifecta_Survey_Question_Choice__c checkBoxOption1 = new Trifecta_Survey_Question_Choice__c(Load_Id__c = TTISGGuidUtil.NewGuid(), 
        											Value__c = 'checkBoxOption1', Survey_Question__c = checkQuestion.Id);
        Trifecta_Survey_Question_Choice__c checkBoxOption2 = new Trifecta_Survey_Question_Choice__c(Load_Id__c = TTISGGuidUtil.NewGuid(), 
        											Value__c = 'checkBoxOption2', Survey_Question__c = checkQuestion.Id);
        choiceList.add(radioButtonOption1);
        choiceList.add(radioButtonOption2);
        choiceList.add(checkBoxOption1);
        choiceList.add(checkBoxOption2);
        insert choiceList;

        Trifecta_Survey_Submission__c surveySubmission = new Trifecta_Survey_Submission__c(Survey__c=survey.id, Submitted_To__c=UserInfo.getUserId());
        insert surveySubmission;

        return survey;
	}
}