src/objects/Trifecta_Survey__c.object
<CustomObject>
    <fields>
        <fullName>Auto_Response_Message__c</fullName>
        <description>Message to be displayed after the submission of the survey</description>
        <label>Auto Response Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Help_Text__c</fullName>
        <description>Inline help text for the purpose of the survey</description>
        <label>Help Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Trifecta Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trifecta Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Trifecta_Survey_Submission__c.object
<CustomObject>
    <description>Junction object to link up Survey and User/Contact to whom the survey is submitted.</description>
    <fields>
        <fullName>Submitted_To__c</fullName>
        <description>Id of User/Contact</description>
        <label>Submitted To</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <description>Survey which is submitted</description>
        <label>Survey</label>
        <referenceTo>Trifecta_Survey__c</referenceTo>
        <relationshipLabel>Trifecta Survey Submissions</relationshipLabel>
        <relationshipName>Trifecta_Survey_Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Trifecta Survey Submission</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Trifecta Survey Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trifecta Survey Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TTISGConfirmationPageControllerTest.cls
@isTest
private class TTISGConfirmationPageControllerTest {
	
	@isTest static void pageDisplayTest() {
	Trifecta_Survey__c survey = setData();
        Trifecta_Survey_Submission__c surveySubmission = [SELECT ID FROM Trifecta_Survey_Submission__c WHERE Survey__c = :survey.ID];
        Test.setCurrentPage(Page.TTISGConfirmation);
        ApexPages.currentPage().getParameters().put('Id',surveySubmission.Id);
        TTISGConfirmationPageController confirmationPage = new TTISGConfirmationPageController();

        System.assertEquals(confirmationPage.confirmationMessage, survey.Auto_Response_Message__c, 'Not Equal');
        
	}
	
	private static Trifecta_Survey__c setData() {
	
        Trifecta_Survey__c survey = new Trifecta_Survey__c(Name='new survey', Auto_Response_Message__c = 'thank you', 
        						Help_Text__c = 'survey help', Load_Id__c = TTISGGuidUtil.NewGuid(),
        						Threshold_Weightage__c = 0);
	insert survey;

	Trifecta_Survey_Submission__c surveySubmission = new Trifecta_Survey_Submission__c(Survey__c=survey.id, Submitted_To__c=UserInfo.getUserId());
        insert surveySubmission;

        return survey;
	}
}