src/objects/Trifecta_Survey__c.object
<CustomObject>
    <label>Trifecta Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trifecta Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Trifecta_Survey_Question__c.object
<CustomObject>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Trifecta_Survey__c</referenceTo>
        <relationshipLabel>Trifecta Survey Questions</relationshipLabel>
        <relationshipName>Trifecta_Survey_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Trifecta Survey Question</label>
    <nameField>
        <displayFormat>SQ-{000000}</displayFormat>
        <label>Trifecta Survey Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trifecta Survey Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Trifecta_Survey_Question_Response__c.object
<CustomObject>
    <label>Trifecta Survey Question Response</label>
    <nameField>
        <displayFormat>SQR-{000000}</displayFormat>
        <label>Trifecta Survey Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trifecta Survey Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Trifecta_Survey_Submission__c.object
<CustomObject>
    <description>Junction object to link up Survey and User/Contact to whom the survey is submitted.</description>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to identify whether the feedback is submitted by the user or not.</description>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Submitted_To__c</fullName>
        <description>Id of User/Contact</description>
        <label>Submitted To</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Trifecta Survey Submission</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Trifecta Survey Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trifecta Survey Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TTISGShareSubmissionToChatterController.cls
public with sharing class TTISGShareSubmissionToChatterController {
    
    public String surveyId;
    public String submissionId;
    
    public TTISGSurveyService surveyService;
    
    public Trifecta_Survey__c survey {get; set;}
    public Trifecta_Survey_Submission__c surveySubmitted{get;set;}
    public List<Trifecta_Survey_Question__c> surveyQuestions {get; set;}
    
    public Map<String,Trifecta_Survey_Question_Response__c> surveyResponses {get; set;}
    
    
    public Map<String,String> surveyQuestionChoiceMap{get;set;} 
    public Map<String,List<String>> checkboxChoiceMap {get; set;}

    public TTISGShareSubmissionToChatterController() {
        surveyId = ApexPages.currentPage().getParameters().get('Survey');
        submissionId = ApexPages.currentPage().getParameters().get('Id');

        surveySubmitted = [select Id, Submitted_To__c, Completed__c from Trifecta_Survey_Submission__c where Id =:submissionId];

        surveyService = new TTISGSurveyService();
        
    	survey = surveyService.getSurveyById(surveyId); 
    	surveyQuestions = survey.Trifecta_Survey_Questions__r;
    	surveyResponses = surveyService.getSurveySubmissionResponses(submissionId);

    }
}