src/objects/Trifecta_Survey__c.object
<CustomObject>
    <label>Trifecta Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trifecta Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Trifecta_Survey_Question__c.object
<CustomObject>
    <fields>
        <fullName>Title__c</fullName>
        <description>Title of the question</description>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Trifecta Survey Question</label>
    <nameField>
        <displayFormat>SQ-{000000}</displayFormat>
        <label>Trifecta Survey Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trifecta Survey Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CreateSurveyController.cls
public class CreateSurveyController {
    
    ApexPages.StandardController controller;
    
    public Trifecta_Survey__c currentSurvey {get; set;}
    
    public CreateSurveyController(ApexPages.StandardController stdController) {
        this.controller = stdController;
        currentSurvey = new Trifecta_Survey__c();
        currentSurvey.Name = 'Untitle form';
    }
    
    public void saveSurvey() {
       System.debug(JSON.serialize(currentSurvey));
        upsert currentSurvey;
    }
    
    public List<Trifecta_Survey_Question__c> getQuestions() {
        Trifecta_Survey_Question__c question = new Trifecta_Survey_Question__c(Title__c='My First Question');
        List<Trifecta_Survey_Question__c> questions = new List<Trifecta_Survey_Question__c>();
        questions.add(question);
        //System.assert(false, json.serializePretty(questions));        
        return questions;
    }
    

}