src/objects/Trifecta_Survey__c.object
<CustomObject>
    <label>Trifecta Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trifecta Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Trifecta_Survey_Question__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of the question ex: Text, Multi Select or Checkbox</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Multi Choice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Trifecta Survey Question</label>
    <nameField>
        <displayFormat>SQ-{000000}</displayFormat>
        <label>Trifecta Survey Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trifecta Survey Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Trifecta_Survey_Question_Choice__c.object
<CustomObject>
    <description>choices for the survey Question</description>
    <fields>
        <fullName>Survey_Question__c</fullName>
        <description>Id of the Survey Question</description>
        <label>Survey Question</label>
        <referenceTo>Trifecta_Survey_Question__c</referenceTo>
        <relationshipLabel>Trifecta Survey Question Choices</relationshipLabel>
        <relationshipName>Trifecta_Survey_Question_Choices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>text for the choice</description>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Trifecta Survey Question Choice</label>
    <nameField>
        <displayFormat>SQC-{0000000}</displayFormat>
        <label>Trifecta Survey Question Choice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trifecta Survey Question Choices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Trifecta_Survey_Question_Response__c.object
<CustomObject>
    <fields>
        <fullName>Answer__c</fullName>
        <description>Choice selected by the User/Contact</description>
        <label>Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Question__c</fullName>
        <description>Id of the Survey Question in current context</description>
        <label>Survey Question</label>
        <referenceTo>Trifecta_Survey_Question__c</referenceTo>
        <relationshipLabel>Trifecta Survey Question Responses</relationshipLabel>
        <relationshipName>Trifecta_Survey_Question_Responses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey_Submission__c</fullName>
        <description>Id of the Survey Submission</description>
        <label>Survey Submission</label>
        <referenceTo>Trifecta_Survey_Submission__c</referenceTo>
        <relationshipLabel>Trifecta Survey Question Responses</relationshipLabel>
        <relationshipName>Trifecta_Survey_Question_Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Trifecta Survey Question Response</label>
    <nameField>
        <displayFormat>SQR-{000000}</displayFormat>
        <label>Trifecta Survey Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trifecta Survey Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Trifecta_Survey_Submission__c.object
<CustomObject>
    <description>Junction object to link up Survey and User/Contact to whom the survey is submitted.</description>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to identify whether the feedback is submitted by the user or not.</description>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Submitted_To__c</fullName>
        <description>Id of User/Contact</description>
        <label>Submitted To</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Trifecta Survey Submission</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Trifecta Survey Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trifecta Survey Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DisplayFormController.cls
public with sharing class DisplayFormController {
	public String surveyId;
 	public String submissionId;
 	public Trifecta_Survey__c survey {get; set;}
 	public Map<String,Trifecta_Survey_Question__c> surveyQuestions{get; set;}
 	public Map<String,List<Trifecta_Survey_Question_Choice__c>> surveyQuestionChoices{get; set;}
 	public List<Trifecta_Survey_Question_Response__c> surveyResponses {get; set;}
 	public static final String CONFIRMATION_PAGE_URL = '/apex/Confirmation?id=';
 	public Map<String,List<SelectOption>> questionChoices {get; set;}
 	public Map<String,String> surveyQuestionChoiceMap{get;set;} 
 	public Map<String,List<String>> checkboxChoiceMap {get; set;}
    public Boolean isSubmittedAlready {get; set;}

 	public DisplayFormController() {
  		surveyId = ApexPages.currentPage().getParameters().get('Survey');
  		submissionId = ApexPages.currentPage().getParameters().get('Id');
  		if ([select Completed__c from Trifecta_Survey_Submission__c where Id=:submissionId].Completed__c ) {
            isSubmittedAlready = true;
  			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'This survey form has been submitted already.'));
  		} else {
  			TrifectaSurveyController.SurveyWrapper surveyData = TrifectaSurveyControllerHelper.createTrifectaSurveyWrapper(surveyId);
  			survey = surveyData.survey;
  			surveyQuestions = surveyData.surveyQuestions;
  			if (surveyQuestions.size() == 1) {
  				List<Trifecta_Survey_Question__c> tempQuestion = surveyQuestions.values();
  				if (tempQuestion[0].Type__c == 'Text') {
  					surveyQuestionChoices = new Map<String, List<Trifecta_Survey_Question_Choice__c>>();
	  			} else {
  					surveyQuestionChoices = surveyData.surveyQuestionChoices;
  				}
  			} else {
	  			surveyQuestionChoices = surveyData.surveyQuestionChoices;
  			}
  			surveyQuestionChoiceMap = new Map<String,String>();
  			checkboxChoiceMap = new Map<String, List<String>>();
	  		questionChoices = new Map<String,List<SelectOption>>();
  			surveyResponses = new List<Trifecta_Survey_Question_Response__c>();
  			for (String eachQuestionId : surveyQuestions.keySet()) {
   				List<SelectOption> tempOptions = new List<SelectOption>();
	   			if (surveyQuestionChoices.size() != 0 && surveyQuestions.get(eachQuestionId).Type__c != 'Text' ) {
		   			for(Trifecta_Survey_Question_Choice__c eachChoice : surveyQuestionChoices.get(eachQuestionId)){
	    				tempOptions.add(new SelectOption(eachChoice.Value__c,eachChoice.Value__c));
   					}
   					questionChoices.put(eachQuestionId, tempOptions);
	   			}
	   			if (surveyQuestions.get(eachQuestionId).Type__c == 'Checkbox') {
	   				checkboxChoiceMap.put(eachQuestionId,new List<String>());
	   			}
	   			else {
   					surveyQuestionChoiceMap.put(eachQuestionId,'');
   				}
  			}	
  		} 
 	}
	public PageReference submitSurvey(){
        //Save the survey before the user can be redirected to Send Survey Page
        saveResponses();
        PageReference confirmationPage = new PageReference(DisplayFormController.CONFIRMATION_PAGE_URL+submissionId);
        confirmationPage.setRedirect(true);
        return confirmationPage;
  	}	


	public void saveResponses() {
  		Trifecta_Survey_Question_Response__c surveyResponse = new Trifecta_Survey_Question_Response__c();
  		for (String eachResponse: surveyQuestions.keySet()) {
  			if (surveyQuestions.get(eachResponse).Type__c == 'Checkbox') {
  				surveyResponse = new Trifecta_Survey_Question_Response__c(Survey_Submission__c=submissionId, 
       							Survey_Question__c = surveyQuestions.get(eachResponse).Id, 
       							Answer__c = String.join(checkboxChoiceMap.get(eachResponse), ','));
  			}
  			else {
  				surveyResponse = new Trifecta_Survey_Question_Response__c(Survey_Submission__c=submissionId, 
       							Survey_Question__c = surveyQuestions.get(eachResponse).Id, 
       							Answer__c = surveyQuestionChoiceMap.get(eachResponse));
  			}
  			surveyResponses.add(surveyResponse);
  		}
  		insert surveyResponses;
  		Trifecta_Survey_Submission__c surveySubmitted = [select id, Completed__c from Trifecta_Survey_Submission__c where Id =:submissionId];
  		surveySubmitted.Completed__c = true;
  		update surveySubmitted;
 	}
  
  public Boolean getUser() {
    Trifecta_Survey_Submission__c submit = [SELECT Id, Submitted_To__c FROM Trifecta_Survey_Submission__c WHERE Id =:submissionId];
    if (submit.Submitted_To__c.substring(0,3) == Schema.getGlobalDescribe().get('User').getDescribe().getKeyPrefix()) {
      return false;
    } else {
      return true;
    }
  }
}