src/objects/Trifecta_Survey_Submission__c.object
<CustomObject>
    <description>Junction object to link up Survey and User/Contact to whom the survey is submitted.</description>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to identify whether the feedback is submitted by the user or not.</description>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Submitted_To__c</fullName>
        <description>Id of User/Contact</description>
        <label>Submitted To</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <description>Survey which is submitted</description>
        <label>Survey</label>
        <referenceTo>Trifecta_Survey__c</referenceTo>
        <relationshipLabel>Trifecta Survey Submissions</relationshipLabel>
        <relationshipName>Trifecta_Survey_Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Trifecta Survey Submission</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Trifecta Survey Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trifecta Survey Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EmailServiceBase.cls
public with sharing class EmailServiceBase implements EmailService {
	public void sendEmailNotifications (List<String> idList, Id surveyId) {
    	List<Messaging.SingleEmailMessage> emailsToSend = new List<Messaging.SingleEmailMessage>();
    	List<Trifecta_Survey_Submission__c> submissionList = new List<Trifecta_Survey_Submission__c>();
        
    	EmailTemplate contactTemplate = [select Id from EmailTemplate where name ='Survey Template Contact'];
        EmailTemplate userTemplate = [select Id from EmailTemplate where name ='Survey Template User'];
        Messaging.SingleEmailMessage[] mails = new List<Messaging.SingleEmailMessage>();
        for(String eachId : idList) {
            submissionList.add(new Trifecta_Survey_Submission__c(Survey__c = surveyId, Submitted_To__c = eachId.trim(), Completed__c = false ));
        
        }
        insert submissionList;
        
    	for(Trifecta_Survey_Submission__c submission : submissionList) {
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            if (submission.Submitted_To__c.substring(0,3) == schema.getGlobalDescribe().get('User').getDescribe().getKeyPrefix()) {
	    	  mail.setTemplateId(userTemplate.Id);
              mail.setSaveAsActivity(false);
            }
            else if (submission.Submitted_To__c.substring(0,3) == schema.getGlobalDescribe().get('Contact').getDescribe().getKeyPrefix()) {
               	mail.setTemplateId(contactTemplate.Id);
                mail.setSaveAsActivity(true);
            }
            mail.setTargetObjectId(submission.Submitted_To__c);
            mail.setWhatId(submission.Id);
            mails.add(mail);
        }
        List<Messaging.SendEmailResult> results = Messaging.sendEmail(mails,false);
    }
}